services:
  # LINE Bot Service
  line-bot:
    build:
      context: services/line-bot
    container_name: gibtee-line-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Database
      DATABASE_URL: mysql://${MYSQL_USER:-gibtee}:${MYSQL_PASSWORD:-password}@192.168.3.100:23306/${MYSQL_DATABASE:-gibtee}

      # LINE Configuration
      LINE_CHANNEL_ACCESS_TOKEN: ${LINE_CHANNEL_ACCESS_TOKEN}
      LINE_CHANNEL_SECRET: ${LINE_CHANNEL_SECRET}

      # AWS Configuration
      AWS_REGION: ${AWS_REGION:-ap-southeast-1}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}

      # Payment Configuration
      LINE_PAY_CHANNEL_ID: ${LINE_PAY_CHANNEL_ID}
      LINE_PAY_CHANNEL_SECRET: ${LINE_PAY_CHANNEL_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}

      # Slack Configuration
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      SLACK_CHANNEL: ${SLACK_CHANNEL:-#gibtee-notifications}
      SLACK_USERNAME: ${SLACK_USERNAME:-gibtee-bot}

      # Service URLs
      IMAGE_PROCESSOR_URL: http://image-processor:4000
    networks:
      - gibtee-network
    volumes:
      - line_bot_logs:/app/logs

  # Image Processor Service
  image-processor:
    build:
      context: ./services/image-processor
    container_name: gibtee-image-processor
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      # Database
      DATABASE_URL: mysql://${MYSQL_USER:-gibtee}:${MYSQL_PASSWORD:-password}@192.168.3.100:23306/${MYSQL_DATABASE:-gibtee}

      # AWS Configuration
      AWS_REGION: ${AWS_REGION:-ap-southeast-1}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}

      # OpenAI Configuration
      OPENAI_API_KEY: ${OPENAI_API_KEY}

      # Service URLs
      LINE_BOT_URL: http://line-bot:3000
    networks:
      - gibtee-network
    volumes:
      - image_uploads:/app/uploads
      - image_processor_logs:/app/logs

  # Admin Panel Service
  admin-panel:
    build:
      context: ./services/admin-panel
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}
    container_name: gibtee-admin-panel
    restart: unless-stopped
    ports:
      - "4001:80"
    environment:
      # API URLs for frontend
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}
    depends_on:
      - line-bot
      - image-processor
    networks:
      - gibtee-network

volumes:
  line_bot_logs:
    driver: local
  image_processor_logs:
    driver: local
  image_uploads:
    driver: local

networks:
  gibtee-network:
    driver: bridge
    name: gibtee-network
