FROM node:18-alpine

# Playwrightの依存関係をインストール
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    nodejs \
    yarn \
    bash \
    curl \
    mysql-client

# 環境変数を設定
ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 \
    PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH=/usr/bin/chromium-browser

WORKDIR /app

# 依存関係をインストール
COPY package*.json ./
RUN npm ci

# プロジェクトファイルをコピー
COPY . .

CMD ["npm", "run", "test:e2e"]